#define SIZE 10
#define FONT_SIZE 80 // best: 80 
#define DISTANCE FONT_SIZE * 2
#define WINDOW_WIDTH 1800 //mudar dps spa pra SIZE * DISTANCE + NUMBER_SIZE
#define WINDOW_HEIGHT 600 // /2
#define ARROW_TEXTURE_OFFSET -50
#define ARROW_DISTANCE_MULTIPLIER 1.5
#define INDEX_TEXTURE_OFFSET 22
#define SPEED 2